### ISSUE TITLE
Create a demo binder

### ISSUE THREAD

**Issue by gnestor** [plotly/jupyterlab-dash#14]
Great work on this! This makes the user experience of developing Dash applications much nicer in my opinion (e.g. develop them in the notebook, preview them in a JupyterLab tab right beside the notebook). 

It would be great to add a binder badge to this repo and allow people to try it out on mybinder. If you're not familiar with binder, see the [reactivepy](https://github.com/jupytercalpoly/reactivepy) repo which has a binder badge that will spin up a fresh JupyterLab environment with all the necessary dependencies installed and demo material included. 

I can help with this. Since Dash starts its own server and mybinder doesn't allow access to arbitrary ports, the implementation will probably require [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy). [dask-labextension](https://github.com/dask/dask-labextension/blob/615b9b04f4e8c17f2001a7327d32425cd77650e0/dask_labextension/dashboardhandler.py) does something similar using nbserverproxy (the former version of jupyter-server-proxy).

**Comment by jonmmease** [comment]
Hi @gnestor, that would be awesome! We also want to get this working in a JupyterHub scenario, which I expect would involve working through the same issues.  I've been meaning to dig into jupyter-server-proxy but haven't gotten to it yet, so any help on working through how this would apply here would be appreciated.

**Comment by gnestor** [comment]
Great! I'm going to see if I can get some sponsored time to work on this. 

I haven't worked with jupyter-server-proxy yet, but we recently used it to [add a _lab-dev_ endpoint to lab](https://github.com/jupyterlab/jupyterlab/pull/5952) that allows us to run lab in dev-mode on mybinder and try out PRs to jupyterlab in binder vs. checking out branches and running them locally.  That PR can serve as reference but the dask-labextension is more relevant to what we want to do here.

**Comment by jonmmease** [comment]
Done!
[![Binder](https://beta.mybinder.org/badge.svg)](https://mybinder.org/v2/gh/plotly/jupyterlab-dash/master?urlpath=lab%2Ftree%2Fnotebooks)
