### ISSUE TITLE
ImportError: No module named 'jupyterlab_dash'

### ISSUE THREAD

**Issue by wanted68** [plotly/jupyterlab-dash#8]
I used the instructions here: https://github.com/plotly/jupyterlab-dash to install dashlab but when I want to `import jupyterlab_dash` there is an error:
``    `     ImportError                               Traceback (most recent call last)
       <ipython-input-166-4bf99b12a09b> in <module>()
        ----> 1 import jupyterlab_dash

    ImportError: No module named 'jupyterlab_dash'`

**Comment by LukaPitamic** [comment]
Same problem here.

**Comment by jtpio** [comment]
`jupyterlab_dash` should also be installed as a Python package from the local folder (since it's not published yet on https://pypi.org).

Can you try running the following commands and restart the kernel?

```bash
# from https://dash.plot.ly/installation

pip install dash==0.35.1  # The core dash backend
pip install dash-html-components==0.13.4  # HTML components
pip install dash-core-components==0.42.1  # Supercharged components
pip install dash-table==3.1.11  # Interactive DataTable component (new!)

# install local package
python -m pip install -e .
```

**Comment by LukaPitamic** [comment]
@jtpio I tried, same problem....
![image](https://user-images.githubusercontent.com/34914144/51769847-5dcf2680-20e4-11e9-909c-5bde6b9ed3d1.png)

**Comment by jtpio** [comment]
Looks like it can be an issue related to the environment.

You could try to create a fresh conda environment using this `environment.yml` file:

```
channels:
- conda-forge
dependencies:
- jupyterlab=0.35
- python=3.7
- pip:
  - dash==0.35.1
  - dash-html-components==0.13.4
  - dash-core-components==0.42.1
  - dash-table==3.1.11
```

Then:
```bash
conda env create -n jupyterlab-dash --file environment.yml
conda activate jupyterlab-dash

python -m pip install -e .

# instructions from https://github.com/plotly/jupyterlab-dash#installation
npm install
npm run build
jupyter labextension link .
```

**Comment by RweSmarter** [comment]
This worked for me.
 Find the generated file jupyterlab_dash  on /Users/name/anaconda3/share/jupyter/lab/extensions/jupyterlab_dash-0.1.0-31a2f982612ec904a6327de29c30a4b59e10aec9.tgz 
Change to the above directory via CD command and install the local package via
pip install .
Don't forget the dot!

**Comment by LukaPitamic** [comment]
solved it - if anyone needs full install procedure (tested on Mac-OSX):

step 0: - if you already have "jupyterlab-dash" env - remove it first
conda env remove -n jupyterlab-dash 
step 1: - put yourself into right directory (took me a while to figure this one out)
cd ~/anaconda3/share/jupyter/lab/extensions
step 2:
git clone https://github.com/plotly/jupyterlab-dash
step 3:
cd jupyterlab-dash
step 4:
npm install
step 5:
npm run build
step 6:
jupyter labextension link .
step 7:
conda env create -n jupyterlab-dash
step 8:
conda activate jupyterlab-dash
step 9:
conda install pip
pip install dash==0.35.1
pip install dash-html-components==0.13.4
pip install dash-core-components==0.42.1
pip install dash-table==3.1.11
step 10:
python -m pip install -e .
step 11:
npm install
step 12:
npm run build
step 13: - DON'T FORGET THE "." !!!!
jupyter labextension link .

Thanks to @RweSmarter & @jtpio 
Rock on!

**Comment by kangnade** [comment]
I am running this from my subsystem Ubuntu on Windows 10, and I followed the steps above, however, got this error message. Is there anyone who could kindly help me with it? Thanks!
![image](https://user-images.githubusercontent.com/22113734/52624197-7b570b00-2eae-11e9-9d7a-d346c13b1b41.png)

**Comment by LukaPitamic** [comment]
@kangnade remove first line since it's not the part of demo code and try again...

**Comment by BravoJuliett** [comment]
From jupyterlab code cell after installing according to [README.md](https://github.com/plotly/jupyterlab-dash):
`import sys`
`sys.path.append("/home/user/<install location(where ever you ran the install steps in the read me file)>/jupyterlab-dash/)`
`import jupterlab_dash`
I struggled with this for a while and this worked for me. I even tried building it in the site-packages directory but still had to point sys to look inside jupyterlab-dash directory.

**Comment by jonmmease** [comment]
Hi All, we've published jupyterlab_dash to PyPI (Python part) and npm (JavaScript part).  Please follow the instructions at https://github.com/plotly/jupyterlab-dash#installation to install using these packages.  I'm going to close this issue since it predates this installation method, but please open a new issue if you have trouble with the installation process while following these instructions.  Thanks!
